---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  licence: SIL
#  licence_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: Just Be Nice studio
  homepage: http://www.justbenicestudio.com/studio/websymbols/
  email: yes@justbenice.ru
  licence: SIL
  licence_url: http://scripts.sil.org/OFL

  css_prefix: "icon-"
  columns: 4


transform:
  baseline: 0.5
  rescale: 0.9
  offset: 0.05


font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: "websymbols"

  fullname: Web Symbols
  familyname: Web Symbols

  copyright: Copyright (c) 2011 by Just Be Nice studio. All rights reserved.

  ascent: 800
  descent: 200
  weight: Medium


glyphs:

  - file: glyph5
    code: 0x0023

  - file: glyph6
    code: 0x0025

  - file: glyph7
    from: 0x0026
    code: 0xe001

  - file: glyph8
    from: 0x0027
    code: 0xe002

  - file: glyph9
    code: 0x0028

  - file: glyph10
    code: 0x0029

  - file: glyph11
    code: 0x002a

  - file: glyph12
    code: 0x002b

  - file: glyph13
    code: 0x002c

  - file: glyph14
    code: 0x002d

  - file: glyph15
    code: 0x002e

  - file: glyph16
    code: 0x002f

  - file: glyph17
    code: 0x0030

  - file: glyph18
    code: 0x0031

  - file: glyph19
    code: 0x0032

  - file: glyph20
    code: 0x0033

  - file: glyph21
    code: 0x0034

  - file: glyph22
    code: 0x0035

  - file: glyph23
    code: 0x0036

  - file: glyph24
    code: 0x0037

  - file: glyph25
    code: 0x003a

  - file: glyph26
    code: 0x003b

  - file: glyph27
    from: 0x003c
    code: 0xe003

  - file: glyph28
    from: 0x003e
    code: 0xe004

  - file: glyph29
    code: 0x003f

  - file: glyph30
    code: 0x0040

  - file: glyph31
    code: 0x0041

  - file: glyph32
    code: 0x0042

  - file: glyph33
    code: 0x0043

  - file: glyph34
    code: 0x0044

  - file: glyph35
    code: 0x0046

  - file: glyph36
    code: 0x0048

  - file: glyph37
    code: 0x0049

  - file: glyph38
    code: 0x004a

  - file: glyph39
    code: 0x004b

  - file: glyph40
    code: 0x004c

  - file: glyph41
    code: 0x004d

  - file: glyph42
    code: 0x004e

  - file: glyph43
    code: 0x004f

  - file: glyph44
    code: 0x0050

  - file: glyph45
    code: 0x0051

  - file: glyph46
    code: 0x0052

  - file: glyph47
    code: 0x0053

  - file: glyph48
    code: 0x0054

  - file: glyph49
    code: 0x0055

  - file: glyph50
    code: 0x0056

  - file: glyph51
    code: 0x0057

  - file: glyph52
    code: 0x0058

  - file: glyph53
    code: 0x005a

  - file: glyph54
    code: 0x005b

  - file: glyph55
    from: 0x005c
    code: 0xe005

  - file: glyph56
    code: 0x005d

  - file: glyph57
    code: 0x005f

  - file: glyph58
    code: 0x0060

  - file: glyph59
    code: 0x0061

  - file: glyph60
    code: 0x0062

  - file: glyph61
    code: 0x0063

  - file: glyph62
    code: 0x0064

  - file: glyph63
    code: 0x0065

  - file: glyph64
    code: 0x0066

  - file: glyph65
    code: 0x0067

  - file: glyph66
    code: 0x0068

  - file: glyph67
    code: 0x0069

  - file: glyph68
    code: 0x006a

  - file: glyph69
    code: 0x006b

  - file: glyph70
    code: 0x006c

  - file: glyph71
    code: 0x006d

  - file: glyph72
    code: 0x006e

  - file: glyph73
    code: 0x006f

  - file: glyph74
    code: 0x0070

  - file: glyph75
    code: 0x0071

  - file: glyph76
    code: 0x0072

  - file: glyph77
    code: 0x0073

  - file: glyph78
    code: 0x0074

  - file: glyph79
    code: 0x0075

  - file: glyph80
    code: 0x0076

  - file: glyph81
    code: 0x0077

  - file: glyph82
    code: 0x0078

  - file: glyph83
    code: 0x0079

  - file: glyph84
    code: 0x007a

  - file: glyph85
    code: 0x007b

  - file: glyph86
    code: 0x007d

  - file: glyph87
    code: 0x007e

  - file: glyph88
    code: 0x00b2

  - file: glyph89
    code: 0x00b3

  - file: glyph90
    code: 0x00b9

  - file: glyph91
    code: 0x00d7

  - file: glyph92
    code: 0xe000
