---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  licence: SIL
#  licence_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: Just Be Nice studio
  homepage: http://www.justbenicestudio.com/studio/websymbols/
  email: yes@justbenice.ru
  licence: SIL
  licence_url: http://scripts.sil.org/OFL

  css_prefix: "icon-"
  columns: 4


transform:
  baseline: 0.5
  rescale: 0.9
  offset: 0.05


font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: "websymbols"

  fullname: Web Symbols
  familyname: Web Symbols

  copyright: Copyright (c) 2011 by Just Be Nice studio. All rights reserved.

  ascent: 800
  descent: 200
  weight: Medium


glyphs:

  - css: search
    code: 0x1f50d
    from: 0x004c
    search: [search, find]

  - css: mail
    code: 0x2709
    from: 0x0040
    search: [mail, email]

  - css: heart
    code: 0x2665
    from: 0x004e
    search: [heart]

  - css: heart-empty
    code: 0x2661
    from: 0x004f
    search: [heart]

  - css: star
    code: 0x2605
    from: 0x0052
    search: [star]

  - css: user
    code: 0x1f464
    from: 0x0055
    search: [profile, contact, user]

  - css: video
    code: 0x1f3ac
    from: 0x004d
    search: [movie, video, film]

  - css: picture
    code: 0x1f304
    from: 0x0049
    search: [image, picture, photo]


  - css: th-large
    code: 0xe708
    from: 0x00b9
    search: [image, list, thumbnails]

  - css: th
    code: 0x268f
    from: 0x00b3
    search: [image, list, thumbnails]

  - css: th-list
    code: 0x2630
    from: 0x00b2
    search: [list]


  - css: ok
    code: 0x2713
    from: 0x002e
    search: [ok, yes, check, mark]

  - css: ok-circle
    code: 0x2714
    from: 0x002f
    search: [ok, yes, check, mark]

  - css: cancel
    code: 0x2715
    from: 0x0027
    search: [close, cancel, reject]

  - css: cancel-circle
    code: 0x2716
    from: 0x00d7
    search: [close, cancel, reject]

  - css: plus-circle
    code: 0x2795
    from: 0x002b
    search: [plus]

  - css: minus-circle
    code: 0x2796
    from: 0x002d
    search: [minus]

  - css: link
    code: 0x1f517
    from: 0x004b
    search: [link, url, address]

  - css: attach
    code: 0x1f4ce
    from: 0x0041
    search: [attach, clip, paperclip]


  - css: lock
    code: 0x1f512
    from: 0x0078
    search: [lock]

  - css: lock-open
    code: 0x1f513
    from: 0x0077
    search: [lock]

  - css: tag
    code: 0xe70c
    from: 0x002c
    search: [tag, price, offer]


  - css: reply
    code: 0xe712
    from: 0x0068
    search: [reply]

  - css: reply-all
    code: 0xe713
    from: 0x0069
    search: [reply]

  - css: forward
    code: 0x27a6
    from: 0x006a
    search: [forward]

  - css: code
    code: 0xe714
    from: 0x0048
    search: [code]

  - css: retweet
    code: 0xe717
    from: 0x004a
    search: [retweet, twitter]


  - css: comment
    code: 0xe718
    from: 0x0063
    search: [comment, reply, write]

  - css: comment-alt
    code: 0xe71a
    from: 0x0064
    search: [comment, reply, write]

  - css: chat
    code: 0xe720
    from: 0x0065
    search: [chat, talk]


  - css: attention
    code: 0x26a0
    from: 0x0057
    search: [attention, warning, alert]

  - css: location
    code: 0xe724
    from: 0x003f
    search: [location, mark, marker]


  - css: doc
    code: 0xe730
    from: 0x0061
    search: [doc, article]

  - css: docs-landscape
    code: 0xe737
    from: 0x0062
    search: [doc, article]

  - css: folder
    code: 0x1f4c1
    from: 0x0046
    search: [folder]

  - css: archive
    code: 0xe738
    from: 0x005a
    search: [archive]

  - css: rss
    code: 0xe73a
    from: 0x0042
    search: [rss]

  - css: rss-alt
    code: 0xe73b
    from: 0x0072
    search: [rss]

  - css: cog
    code: 0x2699
    from: 0x0053
    search: [settings, cog, gear]

  - css: logout
    code: 0xe741
    from: 0x0058
    search: [logout, signout, exit]

  - css: clock
    code: 0x1f554
    from: 0x0050
    search: [clock, time]

  - css: block
    code: 0x1f6ab
    from: 0x005c
    search: [block, deny]

  - css: resize-full
    code: 0xe744
    from: 0x0025
    search: [resize, fullscreen]

  - css: resize-full-circle
    code: 0xe7a6
    from: 0x0026
    search: [resize, fullscreen]


  - css: popup
    code: 0xe74c
    from: 0x0044
    search: [popup, window]


  - css: left-open
    code: 0xe75d
    from: 0x003c
    search: [arrow, left]

  - css: right-open
    code: 0xe75e
    from: 0x003e
    search: [arrow, right]

  - css: down-circle
    code: 0xe4a4
    from: 0x003b
    search: [arrow, down]
  - css: left-circle
    code: 0xe4a1
    from: 0x0028
    search: [arrow, left]
  - css: right-circle
    code: 0xe4a2
    from: 0x0029
    search: [arrow, right]
  - css: up-circle
    code: 0xe4a3
    from: 0x003a
    search: [arrow, up]


  - css: down-dir
    code: 0x25be
    from: 0x005b
    search: [arrow, down]
  - css: right-dir
    code: 0x25b8
    from: 0x005d
    search: [arrow, right]

  - css: down-micro
    code: 0xe7a7
    from: 0x007b
    search: [arrow, down]
  - css: up-micro
    code: 0xe7a8
    from: 0x007d
    search: [arrow, right]


  - css: cw-circle
    code: 0xe7a9
    from: 0x002a
    search: [reload, redo, repeat]

  - css: arrows-cw
    code: 0xe760
    from: 0x0056
    search: [reload, refresh, update, sync]

  - css: updown-circle
    code: 0xe7aa
    from: 0x007e
    search: [arrow, move]

  - css: target
    code: 0x1f3af
    from: 0x0060
    search: [target]

  - css: signal
    code: 0x1f4f6
    from: 0x0075
    search: [chart, bar, diagram, signal, wifi]


  - css: progress
    code: 0xe7ab
    from: 0x0030
    search: [progress, wait]

# Use CSS rotation! KISS!
#  - file: glyph18
#    code: 0x0031
#  - file: glyph19
#    code: 0x0032
#  - file: glyph20
#    code: 0x0033
#  - file: glyph21
#    code: 0x0034
#  - file: glyph22
#    code: 0x0035
#  - file: glyph23
#    code: 0x0036
#  - file: glyph24
#    code: 0x0037


  - css: font
    code: 0xe779
    from: 0x0054
    search: [editor, font]

  - css: list
    code: 0xe782
    from: 0x0070
    search: [editor, list]

  - file: list-numbered
    code: 0xe7ad
    from: 0x0071
    search: [editor, list]

  - css: indent-left
    code: 0xe783
    from: 0x006f
    search: [editor, indent]

  - css: indent-right
    code: 0xe784
    from: 0x006e
    search: [editor, indent]


  - css: cloud
    code: 0x2601
    from: 0x0043
    search: [cloud]

  - css: terminal
    code: 0xe7ac
    from: 0x005f
    search: [terminal, prompt]

# WTF?
#  - file: glyph92
#    code: 0xe000

# JustBeNice logo
#  - file: glyph5
#    code: 0x0023

  - css: facebook-rect
    code: 0xf301
    from: 0x0066
    search: [facebook]

  - css: twitter-bird
    code: 0xf303
    from: 0x0074
    search: [twitter]

  - css: vimeo-rect
    code: 0xf30e
    from: 0x006d
    search: [vimeo]

  - css: tumblr-rect
    code: 0xf310
    from: 0x006b
    search: [tumblr]

  - css: googleplus-rect
    code: 0xf309
    from: 0x0067
    search: [google]

  - css: linkedin-rect
    code: 0xf312
    from: 0x006c
    search: [linkedin]

  - css: skype
    code: 0xf30b
    from: 0x0073
    search: [skype]

  - css: vkontakte-rect
    code: 0xf30a
    from: 0x0076
    search: [vkontakte]

  - css: youtube
    code: 0xf313
    from: 0x0079
    searcj: [youtube]

# WTF?
#  - css: lettery
#    code: 0x007a

  - css: odnoklassniki-rect
    code: 0xf30d
    from: 0x0051
    search: [odnoklassniki]

